### ISSUE TITLE
Zellij: unable to install on m1 mac

### ISSUE THREAD

**Issue by Lilja** [jsnjack/grm#6]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/6134511/207365761-f31f4ee8-96bf-4e81-a87d-c4d4702929c8.png">

Releases:
https://github.com/zellij-org/zellij/releases
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/6134511/207365885-8b5b0517-eec5-4dce-a56e-5715b0012c65.png">

There is an aarch64 but not found?

```yaml
    zellij-org/zellij:
        repo: zellij
        owner: zellij-org
        version: v0.34.4
        md5: c8909d3ba9b1fe13d35e0c5741ee08d0
        filter: []
        locked: false
        filename: /usr/local/bin/zellij
```
